### ISSUE TITLE
DiscreteProblem seems to not track user defined values

### ISSUE THREAD

**Issue by aytekinar** [JuliaDiffEq/DiffEqBase.jl#41]
I think the `DiscreteProblem` is not tracking the user defined types properly.

Minimal working example below:

```julia
A = diagm([0.3,0.6,0.9])
B = [1 2 3].'
C = [1/3 1/3 1/3]

type SimType{T} <: DEDataArray{T}
    x::Vector{T}
    y::Vector{T}
    u::Vector{T}
end

function mysystem(t,x,dx,u)
    ucalc = u(t,x)
    x.u = ucalc
    x.y = C*x.x
    dx[:] = A*x.x + B*x.u
end

input = (t,x)->(1*one(t)≤t≤2*one(t)?[one(t)]:[zero(t)])
prob = DiscreteProblem((t,x,dx)->mysystem(t,x,dx,input), SimType(zeros(3), zeros(1), zeros(1)), (0.,4.))
sln = solve(prob, FunctionMap(scale_by_time=false), dt = 0.1)

u1 = [sln[idx].u for idx in 1:length(sln)]
u2 = [sln(t).u for t in linspace(0,4,41)]
any(x->x[1]>0, u1)
any(x->x[1]>0, u2)
```

Neither `getindex(sln::SolutionType, idx::Int)` nor `(sln::SolutionType)(t::Real)` seem to be doing what they are supposed to be, if I am not doing any other stupid mistake in calling the functions or defining my objects :( The states (`u`s) seem to be working properly.

**Comment by ChrisRackauckas** [comment]
Fixed on DiffEqBase and OrdinaryDiffEq master. Added to OrdinaryDiffEq tests. 

Note that in real cases, you may want to avoid roundoff error. Adding `dt=0.1` 20 times gives `2.000000002 > 2.0`. This actually doesn't cause a problem here since time on the left endpoint is what matters, but there could be cases where this causes an error. Luckily, Julia has rational numbers for this:

```julia
prob = DiscreteProblem((t,x,dx)->mysystem(t,x,dx,input), SimType(zeros(3), zeros(1), zeros(1)), (0//1,4//1))
sln = solve(prob, FunctionMap(scale_by_time=false), dt = 1//10)

u1 = [sln[idx].u for idx in 1:length(sln)]
u2 = [sln(t).u for t in linspace(0,4,41)]
```

**Comment by ChrisRackauckas** [comment]
I was a little quick on this. This is actually trickier than I thought...

**Comment by aytekinar** [comment]
So, is it fixed, or not fixed? I could not understand it :)

Thanks for the tip, by the way, on `dt = 0.1` :)

**Comment by ChrisRackauckas** [comment]
it's fixed, but there are much larger changes afoot. Master is a scary place right now.
